# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Quorra\Python-Projects\Sorting-Algorithms-Visualisation\matrix_operations_ui_algorithms_project.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1220, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1220, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1220, 900))
        MainWindow.setStyleSheet("#MainWindow{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.193545, x2:1, y2:0.676, stop:0 rgba(30, 187, 114, 255), stop:1 rgba(122, 89, 196, 255));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.create_matrix_btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.create_matrix_btn_1.setEnabled(True)
        self.create_matrix_btn_1.setGeometry(QtCore.QRect(70, 520, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.create_matrix_btn_1.setFont(font)
        self.create_matrix_btn_1.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.create_matrix_btn_1.setStyleSheet("#create_matrix_btn_1{\n"
"background-color: rgb(102, 61, 54);\n"
"border-radius: 10px ;\n"
"color: white;}\n"
"\n"
"#create_matrix_btn_1:hover{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.625, y2:0.761, stop:0 rgba(48, 33, 14, 255), stop:1 rgba(0, 108, 80, 255));\n"
"}")
        self.create_matrix_btn_1.setObjectName("create_matrix_btn_1")
        self.multiply_btn = QtWidgets.QPushButton(self.centralwidget)
        self.multiply_btn.setEnabled(True)
        self.multiply_btn.setGeometry(QtCore.QRect(560, 200, 71, 71))
        self.multiply_btn.setMinimumSize(QtCore.QSize(71, 71))
        self.multiply_btn.setMaximumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.multiply_btn.setFont(font)
        self.multiply_btn.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.multiply_btn.setStyleSheet("#multiply_btn{\n"
"background-color: rgb(80, 61, 54);\n"
"border-radius: 10px ;\n"
"color: white;}\n"
"\n"
"#multiply_btn:hover{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.625, y2:0.761, stop:0 rgba(48, 33, 14, 255), stop:1 rgba(0, 108, 80, 255));\n"
"}")
        self.multiply_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/multiply.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.multiply_btn.setIcon(icon)
        self.multiply_btn.setIconSize(QtCore.QSize(70, 70))
        self.multiply_btn.setObjectName("multiply_btn")
        self.clear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_btn.setGeometry(QtCore.QRect(540, 120, 60, 60))
        self.clear_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.clear_btn.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.clear_btn.setStyleSheet("#clear_btn:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0.0113636, y1:0.591, x2:1, y2:0.25, stop:0 rgba(230, 184, 87, 255), stop:1 rgba(73, 142, 152, 255));\n"
"\n"
"}\n"
"\n"
"#clear_btn{\n"
"background-color: rgba(255, 255, 255,0);\n"
"}")
        self.clear_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/clean.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_btn.setIcon(icon1)
        self.clear_btn.setIconSize(QtCore.QSize(80, 45))
        self.clear_btn.setObjectName("clear_btn")
        self.generate_matrix_btn = QtWidgets.QPushButton(self.centralwidget)
        self.generate_matrix_btn.setGeometry(QtCore.QRect(520, 50, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.generate_matrix_btn.setFont(font)
        self.generate_matrix_btn.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.generate_matrix_btn.setStyleSheet("#generate_matrix_btn{\n"
"background-color: rgb(102, 61, 54);\n"
"border-radius: 10px ;\n"
"color: white;}\n"
"\n"
"#generate_matrix_btn:hover{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.625, y2:0.761, stop:0 rgba(48, 33, 14, 255), stop:1 rgba(0, 108, 80, 255));\n"
"}")
        self.generate_matrix_btn.setObjectName("generate_matrix_btn")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(520, 440, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pushButton_clear_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear_3.setGeometry(QtCore.QRect(600, 120, 60, 60))
        self.pushButton_clear_3.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_clear_3.setFont(font)
        self.pushButton_clear_3.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.pushButton_clear_3.setStyleSheet("#pushButton_clear_3:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0.0113636, y1:0.591, x2:1, y2:0.25, stop:0 rgba(230, 184, 87, 255), stop:1 rgba(73, 142, 152, 255));\n"
"}\n"
"\n"
"#pushButton_clear_3{\n"
"background-color: rgba(255, 255, 255,0);\n"
"}")
        self.pushButton_clear_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/images/excel_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_clear_3.setIcon(icon2)
        self.pushButton_clear_3.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_clear_3.setObjectName("pushButton_clear_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(950, 160, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.pushButton_clear_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear_2.setGeometry(QtCore.QRect(1120, 10, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_clear_2.setFont(font)
        self.pushButton_clear_2.setStyleSheet("#pushButton_clear_2:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0.0113636, y1:0.591, x2:1, y2:0.25, stop:0 rgba(230, 184, 87, 255), stop:1 rgba(73, 142, 152, 255));\n"
"\n"
"}\n"
"\n"
"#pushButton_clear_2{\n"
"background-color: rgba(255, 255, 255,0);\n"
"}")
        self.pushButton_clear_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/images/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_clear_2.setIcon(icon3)
        self.pushButton_clear_2.setIconSize(QtCore.QSize(100, 50))
        self.pushButton_clear_2.setObjectName("pushButton_clear_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(140, 160, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.create_matrix_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.create_matrix_btn_2.setEnabled(True)
        self.create_matrix_btn_2.setGeometry(QtCore.QRect(920, 520, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.create_matrix_btn_2.setFont(font)
        self.create_matrix_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.create_matrix_btn_2.setStyleSheet("#create_matrix_btn_2{\n"
"background-color: rgb(102, 61, 54);\n"
"border-radius: 10px ;\n"
"color: white;}\n"
"\n"
"#create_matrix_btn_2:hover{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.625, y2:0.761, stop:0 rgba(48, 33, 14, 255), stop:1 rgba(0, 108, 80, 255));\n"
"}")
        self.create_matrix_btn_2.setObjectName("create_matrix_btn_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(60, 590, 191, 21))
        self.label_8.setObjectName("label_8")
        self.determinant_btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.determinant_btn_1.setGeometry(QtCore.QRect(80, 630, 141, 28))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.determinant_btn_1.setFont(font)
        self.determinant_btn_1.setStyleSheet("#determinant_btn_1{\n"
"background-color: rgb(102, 61, 54);\n"
"border-radius: 10px ;\n"
"color: white;}\n"
"\n"
"#determinant_btn_1:hover{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.625, y2:0.761, stop:0 rgba(48, 33, 14, 255), stop:1 rgba(0, 108, 80, 255));\n"
"}")
        self.determinant_btn_1.setObjectName("determinant_btn_1")
        self.display_det_1 = QtWidgets.QLabel(self.centralwidget)
        self.display_det_1.setGeometry(QtCore.QRect(230, 630, 64, 28))
        self.display_det_1.setMinimumSize(QtCore.QSize(64, 28))
        self.display_det_1.setMaximumSize(QtCore.QSize(64, 28))
        self.display_det_1.setStyleSheet("background-color: rgb(255, 212, 169);\n"
"border-radius: 10px ;\n"
"border-width: 3px;\n"
"border-color: rgb(170,74,48);")
        self.display_det_1.setText("")
        self.display_det_1.setAlignment(QtCore.Qt.AlignCenter)
        self.display_det_1.setObjectName("display_det_1")
        self.rank_1 = QtWidgets.QLabel(self.centralwidget)
        self.rank_1.setGeometry(QtCore.QRect(230, 750, 64, 28))
        self.rank_1.setMinimumSize(QtCore.QSize(64, 28))
        self.rank_1.setMaximumSize(QtCore.QSize(64, 28))
        self.rank_1.setStyleSheet("background-color: rgb(255, 212, 169);\n"
"border-radius: 10px ;\n"
"border-width: 3px;\n"
"border-color: rgb(170,74,48);")
        self.rank_1.setText("")
        self.rank_1.setAlignment(QtCore.Qt.AlignCenter)
        self.rank_1.setObjectName("rank_1")
        self.multiplyby_btn = QtWidgets.QPushButton(self.centralwidget)
        self.multiplyby_btn.setGeometry(QtCore.QRect(80, 790, 141, 28))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.multiplyby_btn.setFont(font)
        self.multiplyby_btn.setStyleSheet("#multiplyby_btn{\n"
"background-color: rgb(102, 61, 54);\n"
"border-radius: 10px ;\n"
"color: white;}\n"
"\n"
"#multiplyby_btn:hover{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.625, y2:0.761, stop:0 rgba(48, 33, 14, 255), stop:1 rgba(0, 108, 80, 255));\n"
"}")
        self.multiplyby_btn.setObjectName("multiplyby_btn")
        self.transpose_btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.transpose_btn_1.setGeometry(QtCore.QRect(80, 710, 141, 28))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.transpose_btn_1.setFont(font)
        self.transpose_btn_1.setStyleSheet("#transpose_btn_1{\n"
"background-color: rgb(102, 61, 54);\n"
"border-radius: 10px ;\n"
"color: white;}\n"
"\n"
"#transpose_btn_1:hover{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.625, y2:0.761, stop:0 rgba(48, 33, 14, 255), stop:1 rgba(0, 108, 80, 255));\n"
"}")
        self.transpose_btn_1.setObjectName("transpose_btn_1")
        self.takenumbermult_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.takenumbermult_1.setGeometry(QtCore.QRect(230, 790, 64, 28))
        self.takenumbermult_1.setMinimumSize(QtCore.QSize(64, 28))
        self.takenumbermult_1.setMaximumSize(QtCore.QSize(64, 28))
        self.takenumbermult_1.setStyleSheet("background-color: rgb(255, 212, 169);\n"
"border-radius: 10px ;\n"
"border-width: 3px;\n"
"border-color: rgb(170,74,48);")
        self.takenumbermult_1.setAlignment(QtCore.Qt.AlignCenter)
        self.takenumbermult_1.setObjectName("takenumbermult_1")
        self.inverse_btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.inverse_btn_1.setGeometry(QtCore.QRect(80, 670, 141, 28))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.inverse_btn_1.setFont(font)
        self.inverse_btn_1.setStyleSheet("#inverse_btn_1{\n"
"background-color: rgb(102, 61, 54);\n"
"border-radius: 10px ;\n"
"color: white;}\n"
"\n"
"#inverse_btn_1:hover{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.625, y2:0.761, stop:0 rgba(48, 33, 14, 255), stop:1 rgba(0, 108, 80, 255));\n"
"}")
        self.inverse_btn_1.setObjectName("inverse_btn_1")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 610, 271, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.rank_btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.rank_btn_1.setGeometry(QtCore.QRect(80, 750, 141, 28))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.rank_btn_1.setFont(font)
        self.rank_btn_1.setStyleSheet("#rank_btn_1{\n"
"background-color: rgb(102, 61, 54);\n"
"border-radius: 10px ;\n"
"color: white;}\n"
"\n"
"#rank_btn_1:hover{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.625, y2:0.761, stop:0 rgba(48, 33, 14, 255), stop:1 rgba(0, 108, 80, 255));\n"
"}")
        self.rank_btn_1.setObjectName("rank_btn_1")
        self.inverse_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.inverse_btn_2.setGeometry(QtCore.QRect(930, 660, 141, 28))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.inverse_btn_2.setFont(font)
        self.inverse_btn_2.setStyleSheet("#inverse_btn_2{\n"
"background-color: rgb(102, 61, 54);\n"
"border-radius: 10px ;\n"
"color: white;}\n"
"\n"
"#inverse_btn_2:hover{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.625, y2:0.761, stop:0 rgba(48, 33, 14, 255), stop:1 rgba(0, 108, 80, 255));\n"
"}")
        self.inverse_btn_2.setObjectName("inverse_btn_2")
        self.multiplyby_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.multiplyby_btn_2.setGeometry(QtCore.QRect(930, 780, 141, 28))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.multiplyby_btn_2.setFont(font)
        self.multiplyby_btn_2.setStyleSheet("#multiplyby_btn_2{\n"
"background-color: rgb(102, 61, 54);\n"
"border-radius: 10px ;\n"
"color: white;}\n"
"\n"
"#multiplyby_btn_2:hover{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.625, y2:0.761, stop:0 rgba(48, 33, 14, 255), stop:1 rgba(0, 108, 80, 255));\n"
"}")
        self.multiplyby_btn_2.setObjectName("multiplyby_btn_2")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(870, 600, 271, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.display_det_2 = QtWidgets.QLabel(self.centralwidget)
        self.display_det_2.setGeometry(QtCore.QRect(1080, 620, 64, 28))
        self.display_det_2.setMinimumSize(QtCore.QSize(64, 28))
        self.display_det_2.setMaximumSize(QtCore.QSize(64, 28))
        self.display_det_2.setStyleSheet("background-color: rgb(255, 212, 169);\n"
"border-radius: 10px ;\n"
"border-width: 3px;\n"
"border-color: rgb(170,74,48);")
        self.display_det_2.setText("")
        self.display_det_2.setAlignment(QtCore.Qt.AlignCenter)
        self.display_det_2.setObjectName("display_det_2")
        self.rank_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.rank_btn_2.setGeometry(QtCore.QRect(930, 740, 141, 28))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.rank_btn_2.setFont(font)
        self.rank_btn_2.setStyleSheet("#rank_btn_2{\n"
"background-color: rgb(102, 61, 54);\n"
"border-radius: 10px ;\n"
"color: white;}\n"
"\n"
"#rank_btn_2:hover{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.625, y2:0.761, stop:0 rgba(48, 33, 14, 255), stop:1 rgba(0, 108, 80, 255));\n"
"}")
        self.rank_btn_2.setObjectName("rank_btn_2")
        self.rank_2 = QtWidgets.QLabel(self.centralwidget)
        self.rank_2.setGeometry(QtCore.QRect(1080, 740, 64, 28))
        self.rank_2.setMinimumSize(QtCore.QSize(64, 28))
        self.rank_2.setMaximumSize(QtCore.QSize(64, 28))
        self.rank_2.setStyleSheet("background-color: rgb(255, 212, 169);\n"
"border-radius: 10px ;\n"
"border-width: 3px;\n"
"border-color: rgb(170,74,48);")
        self.rank_2.setText("")
        self.rank_2.setAlignment(QtCore.Qt.AlignCenter)
        self.rank_2.setObjectName("rank_2")
        self.transpose_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.transpose_btn_2.setGeometry(QtCore.QRect(930, 700, 141, 28))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.transpose_btn_2.setFont(font)
        self.transpose_btn_2.setStyleSheet("#transpose_btn_2{\n"
"background-color: rgb(102, 61, 54);\n"
"border-radius: 10px ;\n"
"color: white;}\n"
"\n"
"#transpose_btn_2:hover{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.625, y2:0.761, stop:0 rgba(48, 33, 14, 255), stop:1 rgba(0, 108, 80, 255));\n"
"}")
        self.transpose_btn_2.setObjectName("transpose_btn_2")
        self.takenumbermult_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.takenumbermult_2.setGeometry(QtCore.QRect(1080, 780, 64, 28))
        self.takenumbermult_2.setMinimumSize(QtCore.QSize(64, 28))
        self.takenumbermult_2.setMaximumSize(QtCore.QSize(64, 28))
        self.takenumbermult_2.setStyleSheet("background-color: rgb(255, 212, 169);\n"
"border-radius: 10px ;\n"
"border-width: 3px;\n"
"border-color: rgb(170,74,48);")
        self.takenumbermult_2.setAlignment(QtCore.Qt.AlignCenter)
        self.takenumbermult_2.setObjectName("takenumbermult_2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(900, 580, 191, 21))
        self.label_9.setObjectName("label_9")
        self.determinant_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.determinant_btn_2.setGeometry(QtCore.QRect(930, 620, 141, 28))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.determinant_btn_2.setFont(font)
        self.determinant_btn_2.setStyleSheet("#determinant_btn_2{\n"
"background-color: rgb(102, 61, 54);\n"
"border-radius: 10px ;\n"
"color: white;}\n"
"\n"
"#determinant_btn_2:hover{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.625, y2:0.761, stop:0 rgba(48, 33, 14, 255), stop:1 rgba(0, 108, 80, 255));\n"
"}")
        self.determinant_btn_2.setObjectName("determinant_btn_2")
        self.Matrix_1 = QtWidgets.QTableWidget(self.centralwidget)
        self.Matrix_1.setGeometry(QtCore.QRect(0, 190, 500, 300))
        self.Matrix_1.setMinimumSize(QtCore.QSize(311, 271))
        self.Matrix_1.setMouseTracking(False)
        self.Matrix_1.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"\n"
"border-color: rgb(170,74,48);\n"
"border-radius: 8px;")
        self.Matrix_1.setAutoScroll(True)
        self.Matrix_1.setObjectName("Matrix_1")
        self.Matrix_1.setColumnCount(0)
        self.Matrix_1.setRowCount(0)
        self.Matrix_1.horizontalHeader().setVisible(False)
        self.Matrix_1.horizontalHeader().setHighlightSections(False)
        self.Matrix_1.verticalHeader().setVisible(False)
        self.Matrix_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.Matrix_2.setGeometry(QtCore.QRect(720, 180, 500, 300))
        self.Matrix_2.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border-width: 3px;\n"
"border-color: rgb(170,74,48);\n"
"border-radius: 8px;")
        self.Matrix_2.setObjectName("Matrix_2")
        self.Matrix_2.setColumnCount(0)
        self.Matrix_2.setRowCount(0)
        self.Matrix_2.horizontalHeader().setVisible(False)
        self.Matrix_2.verticalHeader().setVisible(False)
        self.resultmatrix = QtWidgets.QTableWidget(self.centralwidget)
        self.resultmatrix.setGeometry(QtCore.QRect(340, 490, 500, 300))
        self.resultmatrix.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border-width: 3px;\n"
"border-color: rgb(170,74,48);\n"
"border-radius: 8px;")
        self.resultmatrix.setObjectName("resultmatrix")
        self.resultmatrix.setColumnCount(0)
        self.resultmatrix.setRowCount(0)
        self.resultmatrix.horizontalHeader().setVisible(False)
        self.resultmatrix.verticalHeader().setVisible(False)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(510, 280, 162, 73))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_multmat_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_multmat_4.setEnabled(True)
        self.pushButton_multmat_4.setMinimumSize(QtCore.QSize(71, 71))
        self.pushButton_multmat_4.setMaximumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_multmat_4.setFont(font)
        self.pushButton_multmat_4.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.pushButton_multmat_4.setStyleSheet("#pushButton_multmat_4{\n"
"background-color: rgb(80, 61, 54);\n"
"border-radius: 10px ;\n"
"color: white;}\n"
"\n"
"#pushButton_multmat_4:hover{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.625, y2:0.761, stop:0 rgba(48, 33, 14, 255), stop:1 rgba(0, 108, 80, 255));\n"
"}")
        self.pushButton_multmat_4.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/images/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_multmat_4.setIcon(icon4)
        self.pushButton_multmat_4.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_multmat_4.setObjectName("pushButton_multmat_4")
        self.horizontalLayout.addWidget(self.pushButton_multmat_4)
        self.pushButton_multmat_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_multmat_3.setEnabled(True)
        self.pushButton_multmat_3.setMinimumSize(QtCore.QSize(71, 71))
        self.pushButton_multmat_3.setMaximumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_multmat_3.setFont(font)
        self.pushButton_multmat_3.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.pushButton_multmat_3.setStyleSheet("#pushButton_multmat_3{\n"
"background-color: rgb(80, 61, 54);\n"
"border-radius: 10px ;\n"
"color: white;}\n"
"\n"
"#pushButton_multmat_3:hover{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.625, y2:0.761, stop:0 rgba(48, 33, 14, 255), stop:1 rgba(0, 108, 80, 255));\n"
"}")
        self.pushButton_multmat_3.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/images/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_multmat_3.setIcon(icon5)
        self.pushButton_multmat_3.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_multmat_3.setObjectName("pushButton_multmat_3")
        self.horizontalLayout.addWidget(self.pushButton_multmat_3)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(940, 20, 142, 112))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.label_11.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.label_7.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.row_m2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.row_m2.setMinimumSize(QtCore.QSize(64, 54))
        self.row_m2.setMaximumSize(QtCore.QSize(64, 54))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.row_m2.setFont(font)
        self.row_m2.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.row_m2.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        self.row_m2.setAlignment(QtCore.Qt.AlignCenter)
        self.row_m2.setObjectName("row_m2")
        self.verticalLayout_3.addWidget(self.row_m2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.column_m2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.column_m2.setMinimumSize(QtCore.QSize(64, 54))
        self.column_m2.setMaximumSize(QtCore.QSize(64, 54))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.column_m2.setFont(font)
        self.column_m2.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.column_m2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.column_m2.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        self.column_m2.setAlignment(QtCore.Qt.AlignCenter)
        self.column_m2.setClearButtonEnabled(False)
        self.column_m2.setObjectName("column_m2")
        self.verticalLayout_4.addWidget(self.column_m2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(140, 20, 142, 112))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.label_10.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.row_m1 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.row_m1.setMinimumSize(QtCore.QSize(64, 54))
        self.row_m1.setMaximumSize(QtCore.QSize(64, 54))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.row_m1.setFont(font)
        self.row_m1.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.row_m1.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        self.row_m1.setAlignment(QtCore.Qt.AlignCenter)
        self.row_m1.setObjectName("row_m1")
        self.verticalLayout.addWidget(self.row_m1)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.column_m1 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.column_m1.setMinimumSize(QtCore.QSize(64, 54))
        self.column_m1.setMaximumSize(QtCore.QSize(64, 54))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.column_m1.setFont(font)
        self.column_m1.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.column_m1.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        self.column_m1.setAlignment(QtCore.Qt.AlignCenter)
        self.column_m1.setObjectName("column_m1")
        self.verticalLayout_2.addWidget(self.column_m1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(480, 10, 221, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.create_matrix_btn_1.setText(_translate("MainWindow", "CREATE MATRIX"))
        self.generate_matrix_btn.setText(_translate("MainWindow", "GENERATE MATRIX"))
        self.label_4.setText(_translate("MainWindow", "Result Matrix :"))
        self.label_5.setText(_translate("MainWindow", "Second Matrix:"))
        self.label_6.setText(_translate("MainWindow", "First Matrix:"))
        self.create_matrix_btn_2.setText(_translate("MainWindow", "CREATE MATRIX"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">First Matrix Operations</span></p></body></html>"))
        self.determinant_btn_1.setToolTip(_translate("MainWindow", "Calculate determinant for Matrix 1"))
        self.determinant_btn_1.setText(_translate("MainWindow", "DETERMINANT"))
        self.multiplyby_btn.setToolTip(_translate("MainWindow", "Multiplying Matrix 1 by the scalar number "))
        self.multiplyby_btn.setText(_translate("MainWindow", "MULTIPLY WITH"))
        self.transpose_btn_1.setToolTip(_translate("MainWindow", "Calculate Transpose for Matrix 1"))
        self.transpose_btn_1.setText(_translate("MainWindow", "TRANSPOSE"))
        self.inverse_btn_1.setToolTip(_translate("MainWindow", "Calculate Inverse Matrix 1"))
        self.inverse_btn_1.setText(_translate("MainWindow", "INVERSE"))
        self.rank_btn_1.setToolTip(_translate("MainWindow", "Calculate Rank for Matrix 1"))
        self.rank_btn_1.setText(_translate("MainWindow", "RANK"))
        self.inverse_btn_2.setToolTip(_translate("MainWindow", "Calculate Inverse Matrix 2"))
        self.inverse_btn_2.setText(_translate("MainWindow", "INVERSE"))
        self.multiplyby_btn_2.setToolTip(_translate("MainWindow", "Multiplying Matrix 2 by the scalar number "))
        self.multiplyby_btn_2.setText(_translate("MainWindow", "MULTIPLY WITH"))
        self.rank_btn_2.setToolTip(_translate("MainWindow", "Calculate Rank for Matrix 2"))
        self.rank_btn_2.setText(_translate("MainWindow", "RANK"))
        self.transpose_btn_2.setToolTip(_translate("MainWindow", "Calculate Transpose for Matrix 2"))
        self.transpose_btn_2.setText(_translate("MainWindow", "TRANSPOSE"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Second Matrix Operations</span></p></body></html>"))
        self.determinant_btn_2.setToolTip(_translate("MainWindow", "Calculate determinant for Matrix 2"))
        self.determinant_btn_2.setText(_translate("MainWindow", "DETERMINANT"))
        self.Matrix_1.setSortingEnabled(False)
        self.label_11.setText(_translate("MainWindow", "Second Matrix"))
        self.label_7.setText(_translate("MainWindow", "Row"))
        self.row_m2.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "Column"))
        self.column_m2.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "First Matrix"))
        self.label.setText(_translate("MainWindow", "Row"))
        self.row_m1.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "Column"))
        self.column_m1.setText(_translate("MainWindow", "0"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-style:italic; color:#000000;\">Matrix Operations</span></p></body></html>"))
import icons_rc
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
