# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Quorra\Python-Projects\Sorting-Algorithms-Visualisation\qt_designer_ozan\fibonacci_uiqt.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FibonacciWindow(object):
    def setupUi(self, FibonacciWindow):
        FibonacciWindow.setObjectName("FibonacciWindow")
        FibonacciWindow.resize(1200, 800)
        FibonacciWindow.setMinimumSize(QtCore.QSize(1200, 800))
        FibonacciWindow.setMaximumSize(QtCore.QSize(4500, 4500))
        FibonacciWindow.setStyleSheet("#FibonacciWindow{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.193545, x2:1, y2:0.676, stop:0 rgba(30, 187, 114, 255), stop:1 rgba(122, 89, 196, 255));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(FibonacciWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_top = QtWidgets.QFrame(self.centralwidget)
        self.frame_top.setMinimumSize(QtCore.QSize(1180, 0))
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_top.setStyleSheet("background-color: transparent;")
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_top_right = QtWidgets.QFrame(self.frame_top)
        self.frame_top_right.setStyleSheet("background: transparent;")
        self.frame_top_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_right.setObjectName("frame_top_right")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_right)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_top_btns = QtWidgets.QFrame(self.frame_top_right)
        self.frame_top_btns.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_top_btns.setStyleSheet("background-color: rgba(33, 45, 76, 150);")
        self.frame_top_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_btns.setObjectName("frame_top_btns")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_top_btns)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_label_top_btns = QtWidgets.QFrame(self.frame_top_btns)
        self.frame_label_top_btns.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_label_top_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_label_top_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_top_btns.setObjectName("frame_label_top_btns")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_label_top_btns)
        self.horizontalLayout_15.setContentsMargins(8, 0, 10, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame_icon_top_bar = QtWidgets.QFrame(self.frame_label_top_btns)
        self.frame_icon_top_bar.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_icon_top_bar.setMaximumSize(QtCore.QSize(30, 30))
        self.frame_icon_top_bar.setStyleSheet("background: transparent;\n"
"image: url(images/shutter_speed_white_24dp.svg);\n"
"background-position: center;\n"
"background-repeat: no-repeat;")
        self.frame_icon_top_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_icon_top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_icon_top_bar.setObjectName("frame_icon_top_bar")
        self.horizontalLayout_15.addWidget(self.frame_icon_top_bar)
        self.label_title_bar_top = QtWidgets.QLabel(self.frame_label_top_btns)
        self.label_title_bar_top.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_title_bar_top.setFont(font)
        self.label_title_bar_top.setStyleSheet("background: transparent;\n"
"margin-left: 5px;\n"
"color: rgb(255, 255, 255);")
        self.label_title_bar_top.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_bar_top.setObjectName("label_title_bar_top")
        self.horizontalLayout_15.addWidget(self.label_title_bar_top)
        self.label_title_bar_top.raise_()
        self.frame_icon_top_bar.raise_()
        self.horizontalLayout_14.addWidget(self.frame_label_top_btns)
        self.frame_btns_right = QtWidgets.QFrame(self.frame_top_btns)
        self.frame_btns_right.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_btns_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_btns_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns_right.setObjectName("frame_btns_right")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_btns_right)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_minimize.sizePolicy().hasHeightForWidth())
        self.btn_minimize.setSizePolicy(sizePolicy)
        self.btn_minimize.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_minimize.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(44, 49, 60)\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_minimize.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Quorra\\Python-Projects\\Sorting-Algorithms-Visualisation\\qt_designer_ozan\\../images/minimize_white_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimize.setIcon(icon)
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_16.addWidget(self.btn_minimize)
        self.btn_maximize_restore = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_maximize_restore.sizePolicy().hasHeightForWidth())
        self.btn_maximize_restore.setSizePolicy(sizePolicy)
        self.btn_maximize_restore.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_maximize_restore.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(44, 49, 60)\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_maximize_restore.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\Quorra\\Python-Projects\\Sorting-Algorithms-Visualisation\\qt_designer_ozan\\../images/open_in_full_white_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_maximize_restore.setIcon(icon1)
        self.btn_maximize_restore.setObjectName("btn_maximize_restore")
        self.horizontalLayout_16.addWidget(self.btn_maximize_restore)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        self.btn_close.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_close.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(44, 49, 60)\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\Quorra\\Python-Projects\\Sorting-Algorithms-Visualisation\\qt_designer_ozan\\../images/close_white_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon2)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_16.addWidget(self.btn_close)
        self.btn_minimize.raise_()
        self.btn_close.raise_()
        self.btn_maximize_restore.raise_()
        self.horizontalLayout_14.addWidget(self.frame_btns_right)
        self.verticalLayout_4.addWidget(self.frame_top_btns)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_13.addWidget(self.frame_top_right)
        self.verticalLayout.addWidget(self.frame_top)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.n_number = QtWidgets.QLineEdit(self.centralwidget)
        self.n_number.setMinimumSize(QtCore.QSize(224, 32))
        self.n_number.setMaximumSize(QtCore.QSize(224, 32))
        self.n_number.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px ;")
        self.n_number.setText("")
        self.n_number.setAlignment(QtCore.Qt.AlignCenter)
        self.n_number.setPlaceholderText("")
        self.n_number.setObjectName("n_number")
        self.horizontalLayout_2.addWidget(self.n_number)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.findfibo_btn = QtWidgets.QPushButton(self.centralwidget)
        self.findfibo_btn.setMinimumSize(QtCore.QSize(272, 28))
        self.findfibo_btn.setMaximumSize(QtCore.QSize(272, 28))
        self.findfibo_btn.setStyleSheet("#findfibo_btn{background-color:rgba(120, 2, 6, 255);\n"
"font: 10pt \"MS Shell Dlg 2\" white;\n"
"border-radius: 10px ;\n"
"color: white;}\n"
"\n"
"#findfibo_btn:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.425318, x2:1, y2:0.341, stop:0 rgba(120, 2, 6, 255), stop:1 rgba(45, 4, 83, 255));}")
        self.findfibo_btn.setObjectName("findfibo_btn")
        self.horizontalLayout_3.addWidget(self.findfibo_btn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setMinimumSize(QtCore.QSize(324, 32))
        self.result.setMaximumSize(QtCore.QSize(324, 32))
        self.result.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(240, 240, 240);\n"
"border-radius: 10px ;")
        self.result.setText("")
        self.result.setAlignment(QtCore.Qt.AlignCenter)
        self.result.setObjectName("result")
        self.horizontalLayout_4.addWidget(self.result)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMinimumSize(QtCore.QSize(151, 21))
        self.label_6.setMaximumSize(QtCore.QSize(151, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.MplFib = MplFib(self.centralwidget)
        self.MplFib.setMinimumSize(QtCore.QSize(860, 276))
        self.MplFib.setMaximumSize(QtCore.QSize(860, 276))
        self.MplFib.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.MplFib.setObjectName("MplFib")
        self.horizontalLayout_5.addWidget(self.MplFib)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMinimumSize(QtCore.QSize(151, 21))
        self.label_7.setMaximumSize(QtCore.QSize(151, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem14)
        self.fibonacci_series = QtWidgets.QLabel(self.centralwidget)
        self.fibonacci_series.setMinimumSize(QtCore.QSize(461, 111))
        self.fibonacci_series.setMaximumSize(QtCore.QSize(461, 111))
        self.fibonacci_series.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(230, 230, 230);\n"
"border-radius: 10px ;")
        self.fibonacci_series.setText("")
        self.fibonacci_series.setAlignment(QtCore.Qt.AlignCenter)
        self.fibonacci_series.setObjectName("fibonacci_series")
        self.horizontalLayout_8.addWidget(self.fibonacci_series)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem15)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem16)
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setMinimumSize(QtCore.QSize(160, 22))
        self.horizontalSlider.setMaximumSize(QtCore.QSize(160, 22))
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(10)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setTickInterval(1)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_9.addWidget(self.horizontalSlider)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem17)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem18)
        self.golden_spiral = QtWidgets.QPushButton(self.centralwidget)
        self.golden_spiral.setMinimumSize(QtCore.QSize(191, 28))
        self.golden_spiral.setMaximumSize(QtCore.QSize(191, 28))
        self.golden_spiral.setStyleSheet("#golden_spiral{\n"
"background-color: rgb(5, 102, 38);\n"
"font: 10pt \"MS Shell Dlg 2\" white;\n"
"border-radius: 10px ;\n"
"color: white;\n"
"}\n"
"#golden_spiral:hover{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.625, y2:0.761, stop:0 rgba(48, 33, 14, 255), stop:1 rgba(0, 108, 80, 255));\n"
"}")
        self.golden_spiral.setObjectName("golden_spiral")
        self.horizontalLayout_10.addWidget(self.golden_spiral)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem19)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem20)
        self.mic_btn = QtWidgets.QPushButton(self.centralwidget)
        self.mic_btn.setMinimumSize(QtCore.QSize(62, 62))
        self.mic_btn.setMaximumSize(QtCore.QSize(62, 62))
        self.mic_btn.setStyleSheet("#mic_btn{background-color: rgba(0,0,0,0);}\n"
"\n"
"#mic_btn:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.453136, x2:1, y2:0.523273, stop:0 rgba(104, 113, 138, 255), stop:1 rgba(215, 221, 232, 255));}")
        self.mic_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/images/microphone.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mic_btn.setIcon(icon3)
        self.mic_btn.setIconSize(QtCore.QSize(50, 50))
        self.mic_btn.setObjectName("mic_btn")
        self.horizontalLayout_12.addWidget(self.mic_btn)
        self.back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.back_btn.setMinimumSize(QtCore.QSize(62, 62))
        self.back_btn.setMaximumSize(QtCore.QSize(62, 62))
        self.back_btn.setStyleSheet("#back_btn{background-color: rgba(0,0,0,0);}\n"
"\n"
"#back_btn:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.453136, x2:1, y2:0.523273, stop:0 rgba(104, 113, 138, 255), stop:1 rgba(215, 221, 232, 255));}")
        self.back_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/images/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_btn.setIcon(icon4)
        self.back_btn.setIconSize(QtCore.QSize(60, 60))
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout_12.addWidget(self.back_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem21)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem22)
        self.clear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_btn.setMinimumSize(QtCore.QSize(111, 28))
        self.clear_btn.setMaximumSize(QtCore.QSize(111, 28))
        self.clear_btn.setStyleSheet("#clear_btn{\n"
"background-color: rgb(5, 102, 38);\n"
"font: 10pt \"MS Shell Dlg 2\" white;\n"
"border-radius: 10px ;\n"
"color: white;\n"
"}\n"
"#clear_btn:hover{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.625, y2:0.761, stop:0 rgba(48, 33, 14, 255), stop:1 rgba(0, 108, 80, 255));\n"
"}")
        self.clear_btn.setObjectName("clear_btn")
        self.horizontalLayout_11.addWidget(self.clear_btn)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem23)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        FibonacciWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(FibonacciWindow)
        self.statusbar.setObjectName("statusbar")
        FibonacciWindow.setStatusBar(self.statusbar)

        self.retranslateUi(FibonacciWindow)
        QtCore.QMetaObject.connectSlotsByName(FibonacciWindow)

    def retranslateUi(self, FibonacciWindow):
        _translate = QtCore.QCoreApplication.translate
        FibonacciWindow.setWindowTitle(_translate("FibonacciWindow", "MainWindow"))
        self.label_title_bar_top.setText(_translate("FibonacciWindow", "Algorithms Project GUI - Fibonacci Number"))
        self.btn_minimize.setToolTip(_translate("FibonacciWindow", "Minimize"))
        self.btn_maximize_restore.setToolTip(_translate("FibonacciWindow", "Maximize"))
        self.btn_close.setToolTip(_translate("FibonacciWindow", "Close"))
        self.n_number.setToolTip(_translate("FibonacciWindow", "Enter a number"))
        self.findfibo_btn.setToolTip(_translate("FibonacciWindow", "Find nth Fibonacci Number"))
        self.findfibo_btn.setText(_translate("FibonacciWindow", "FIND I\'TH FIBONACCI NUMBER"))
        self.result.setToolTip(_translate("FibonacciWindow", "Nth Fibonacci Number"))
        self.label_6.setText(_translate("FibonacciWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-style:italic; color:#000000;\">Fibonacci Numbers</span></p></body></html>"))
        self.label_7.setText(_translate("FibonacciWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-style:italic; color:#000000;\">Fibonacci Array</span></p></body></html>"))
        self.fibonacci_series.setToolTip(_translate("FibonacciWindow", "Fibonacci Sequence"))
        self.horizontalSlider.setToolTip(_translate("FibonacciWindow", "Set for Fibonacci spiral"))
        self.golden_spiral.setToolTip(_translate("FibonacciWindow", "See the Fibonacci Spiral"))
        self.golden_spiral.setText(_translate("FibonacciWindow", "FIBONACCI SPIRAL"))
        self.mic_btn.setToolTip(_translate("FibonacciWindow", "Speech Recognition"))
        self.back_btn.setToolTip(_translate("FibonacciWindow", "Back To Menu"))
        self.clear_btn.setToolTip(_translate("FibonacciWindow", "Clear all values"))
        self.clear_btn.setText(_translate("FibonacciWindow", "CLEAR"))
from mplfib import MplFib
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FibonacciWindow = QtWidgets.QMainWindow()
    ui = Ui_FibonacciWindow()
    ui.setupUi(FibonacciWindow)
    FibonacciWindow.show()
    sys.exit(app.exec_())
